### ISSUE TITLE
locking out old browsers

### ISSUE THREAD

**Issue by JonathanMH** [RavingAPD/Schedule-app#2]
It would be beneficial to the project if we tested for the localStorage API being present, if not, we need to come up with a solution on how to proceed. Is there a way?

Also we should maybe save somewhere if the browser supports notifications (try internet explorer / edge), further: save if the user actively says no, if we can get this info.

**Comment by R4ver** [comment]
localStorage is supported in IE11, but notifications are not.

**Comment by JonathanMH** [comment]
Can you create an element on the **HOME** page, that shows the available features as following graphic suggests?

Please make it look prettier than my sketch though.

https://sketch.io/render/sketch55e594383bdd9.png

**Comment by R4ver** [comment]
Element created, just need to commit.
